### ISSUE TITLE
Add github-actions to depandabot 

### ISSUE THREAD

**Issue by NigelBreslaw** [NigelBreslaw/guardian-ghost#87]
```
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: "/"
    schedule:
      interval: "weekly"
```
